"""Natural Language Processing & Preference Extraction Service.

Extracts structured UserPreferences from free-text user requests using Google Gemini
with an automatic offline heuristic fallback.

Key properties:
  - Model calls are strictly confined to intent and preference extraction.
  - Candidate recommendation titles are never generated by the model.
  - Model outputs are sanitized and validated against the verified catalog taxonomy.
  - If GEMINI_API_KEY is missing or the external call fails, the system transitions
    transparently to a local keyword heuristic without crashing.
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from services.catalog_service import CatalogService, get_catalog_service
from services.recommender import UserPreferences

logger = logging.getLogger(__name__)

DEFAULT_MODEL_NAME = "gemini-2.5-flash"


@dataclass
class ExtractionResult:
    """Encapsulates the result of natural-language preference extraction."""

    preferences: UserPreferences
    extraction_mode: str  # "gemini" or "fallback_heuristic"
    fallback_used: bool
    fallback_reason: Optional[str] = None
    raw_response: Optional[str] = None


class GeminiService:
    """Manages natural-language query interpretation using Google Gemini or local fallback."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
        catalog_service: Optional[CatalogService] = None,
    ) -> None:
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        self.model_name = (
            model_name
            or os.environ.get("GEMINI_MODEL")
            or DEFAULT_MODEL_NAME
        )
        self.catalog_service = catalog_service or get_catalog_service()
        self._client: Optional[Any] = None

        if self.api_key and self.api_key.strip():
            self._init_gemini_client()

    def _init_gemini_client(self) -> None:
        """Initializes the google-genai Client safely."""
        try:
            from google import genai
            self._client = genai.Client(api_key=self.api_key.strip())
        except Exception as exc:
            logger.warning("Could not initialize google-genai Client: %s", exc)
            self._client = None

    def is_available(self) -> bool:
        """Returns True if a configured Gemini client is ready."""
        return self._client is not None and bool(self.api_key and self.api_key.strip())

    def extract_preferences(self, query: str) -> ExtractionResult:
        """Interprets a natural-language viewing request into structured UserPreferences.

        Attempts Google Gemini extraction first. If unconfigured or on error,
        transparently switches to the local deterministic heuristic extractor.
        """
        clean_query = str(query or "").strip()
        if not clean_query:
            return ExtractionResult(
                preferences=UserPreferences(),
                extraction_mode="fallback_heuristic",
                fallback_used=True,
                fallback_reason="Empty query provided",
            )

        if self.is_available():
            try:
                prefs, raw_text = self._extract_with_gemini(clean_query)
                return ExtractionResult(
                    preferences=prefs,
                    extraction_mode="gemini",
                    fallback_used=False,
                    fallback_reason=None,
                    raw_response=raw_text,
                )
            except Exception as exc:
                # Never log raw exception if it might contain sensitive data
                err_msg = f"{type(exc).__name__}: {str(exc)[:120]}"
                logger.warning("Gemini extraction failed, engaging local fallback: %s", err_msg)
                prefs = self.extract_with_local_heuristic(clean_query)
                return ExtractionResult(
                    preferences=prefs,
                    extraction_mode="fallback_heuristic",
                    fallback_used=True,
                    fallback_reason=f"Gemini API unavailable: {err_msg}",
                )

        # Fallback when API key is missing
        prefs = self.extract_with_local_heuristic(clean_query)
        return ExtractionResult(
            preferences=prefs,
            extraction_mode="fallback_heuristic",
            fallback_used=True,
            fallback_reason="AI service not configured; running local heuristic extractor",
        )

    def _extract_with_gemini(self, query: str) -> Tuple[UserPreferences, str]:
        """Invokes Gemini model to extract structured preferences in JSON format."""
        from google.genai import types

        genres = self.catalog_service.get_unique_genres()
        moods = self.catalog_service.get_unique_moods()
        languages = self.catalog_service.get_unique_languages()

        system_instruction = (
            "You are a movie and series preference analyzer. Your task is to extract viewing "
            "preferences from the user's natural-language query into structured JSON.\n"
            "DO NOT suggest titles. DO NOT invent movies or series. ONLY extract preferences.\n\n"
            f"Available Taxonomy:\n"
            f"- Supported Genres: {json.dumps(genres)}\n"
            f"- Supported Moods: {json.dumps(moods)}\n"
            f"- Supported Languages: {json.dumps(languages)}\n"
            "- Supported Content Types: ['Movie', 'Series']\n\n"
            "Output must strictly adhere to this JSON structure:\n"
            "{\n"
            '  "genres": ["string"],\n'
            '  "language": "string or null",\n'
            '  "content_type": "Movie" | "Series" | null,\n'
            '  "moods": ["string"],\n'
            '  "tags": ["thematic keywords from query"],\n'
            '  "max_duration_minutes": integer or null,\n'
            '  "duration_category": "quick" | "standard" | "epic" | null\n'
            "}"
        )

        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            response_mime_type="application/json",
            temperature=0.1,
        )

        prompt = f"User Request: {query}"
        response = self._client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config=config,
        )

        response_text = response.text if hasattr(response, "text") else str(response)
        parsed = json.loads(response_text)

        if not isinstance(parsed, dict):
            raise ValueError(f"Expected JSON object from model, got {type(parsed).__name__}")

        validated_prefs = self.validate_and_normalize_taxonomy(parsed)
        return validated_prefs, response_text

    def extract_with_local_heuristic(self, query: str) -> UserPreferences:
        """Deterministic local preference extraction using catalog taxonomy and regex matching.

        Ensures full offline resilience without external dependencies.
        """
        text = query.lower()
        known_genres = self.catalog_service.get_unique_genres()
        known_moods = self.catalog_service.get_unique_moods()
        known_languages = self.catalog_service.get_unique_languages()

        # Genre aliases / adjectival forms
        genre_aliases = {
            "animated": "Animation",
            "anime": "Animation",
            "scifi": "Sci-Fi",
            "sci fi": "Sci-Fi",
            "romantic": "Romance",
            "dramatic": "Drama",
            "historical": "History",
            "musical": "Music",
            "adventurous": "Adventure",
            "comedies": "Comedy",
            "spooky": "Horror",
        }

        # 1. Match Genres
        detected_genres: List[str] = []
        for g in known_genres:
            pattern = r"\b" + re.escape(g.lower()).replace(r"\-", r"[- ]?") + r"\b"
            if re.search(pattern, text):
                detected_genres.append(g)

        for alias, canonical in genre_aliases.items():
            if re.search(r"\b" + re.escape(alias) + r"\b", text):
                if canonical in known_genres and canonical not in detected_genres:
                    detected_genres.append(canonical)

        # 2. Match Moods
        detected_moods: List[str] = []
        for m in known_moods:
            pattern = r"\b" + re.escape(m.lower()).replace(r"\-", r"[- ]?") + r"\b"
            if re.search(pattern, text):
                detected_moods.append(m)

        # 3. Match Language
        detected_language: Optional[str] = None
        for lang in known_languages:
            if re.search(r"\b" + re.escape(lang.lower()) + r"\b", text):
                detected_language = lang
                break

        # 4. Match Content Type
        detected_type: Optional[str] = None
        if re.search(r"\b(series|tv show|show|shows|seasons)\b", text):
            detected_type = "Series"
        elif re.search(r"\b(movie|movies|film|films)\b", text):
            detected_type = "Movie"

        # 5. Match Duration
        max_duration: Optional[int] = None
        duration_cat: Optional[str] = None

        # Matches "under 2 hours", "under two hours", "< 2 hours", "less than 2 hrs"
        hour_match = re.search(
            r"(?:under|less than|within|max|<|at most)\s+(one|two|three|\d+)\s*(?:hours?|hrs?)",
            text,
        )
        if hour_match:
            val_str = hour_match.group(1)
            num_map = {"one": 1, "two": 2, "three": 3}
            hrs = num_map.get(val_str, int(val_str) if val_str.isdigit() else 0)
            if hrs > 0:
                max_duration = hrs * 60

        # Matches "under 90 mins", "< 100 minutes"
        min_match = re.search(
            r"(?:under|less than|within|max|<|at most)\s+(\d+)\s*(?:mins?|minutes?)",
            text,
        )
        if min_match:
            max_duration = int(min_match.group(1))

        if re.search(r"\b(quick|short)\b", text):
            duration_cat = "quick"
            if not max_duration:
                max_duration = 90
        elif re.search(r"\b(epic|long|binge)\b", text):
            duration_cat = "epic"

        # 6. Thematic tags from leftover interesting words
        tag_tokens = re.findall(r"\b[a-z]{4,}\b", text)
        stop_words = {
            "want", "like", "movie", "movies", "series", "show", "shows", "film",
            "films", "watch", "give", "find", "looking", "about", "under", "hours",
            "than", "with", "from", "that", "some", "good", "best", "recommend",
            "preferably", "prefer", "maybe", "please", "something", "really", "need"
        }
        already_categorized = {
            *(g.lower() for g in detected_genres),
            *(m.lower() for m in detected_moods),
            (detected_language.lower() if detected_language else ""),
            (detected_type.lower() if detected_type else ""),
        }
        detected_tags = [
            t for t in tag_tokens
            if t not in stop_words and t not in already_categorized
        ]

        return UserPreferences(
            genres=detected_genres,
            language=detected_language,
            content_type=detected_type,
            moods=detected_moods,
            tags=detected_tags[:5],
            max_duration_minutes=max_duration,
            duration_category=duration_cat,
        )

    def validate_and_normalize_taxonomy(self, raw_data: Dict[str, Any]) -> UserPreferences:
        """Sanitizes raw model output and enforces catalog taxonomy constraints."""
        known_genres_map = {g.lower(): g for g in self.catalog_service.get_unique_genres()}
        known_moods_map = {m.lower(): m for m in self.catalog_service.get_unique_moods()}
        known_languages_map = {l.lower(): l for l in self.catalog_service.get_unique_languages()}

        # 1. Normalize Genres
        raw_genres = raw_data.get("genres") or []
        if isinstance(raw_genres, str):
            raw_genres = [raw_genres]
        valid_genres: List[str] = []
        for g in raw_genres:
            if isinstance(g, str):
                canonical = known_genres_map.get(g.strip().lower())
                if canonical and canonical not in valid_genres:
                    valid_genres.append(canonical)

        # 2. Normalize Moods and Tags
        raw_moods = raw_data.get("moods") or []
        if isinstance(raw_moods, str):
            raw_moods = [raw_moods]
        valid_moods: List[str] = []
        overflow_tags: List[str] = []
        for m in raw_moods:
            if isinstance(m, str):
                canonical = known_moods_map.get(m.strip().lower())
                if canonical and canonical not in valid_moods:
                    valid_moods.append(canonical)
                elif m.strip():
                    overflow_tags.append(m.strip().lower())

        raw_tags = raw_data.get("tags") or []
        if isinstance(raw_tags, str):
            raw_tags = [raw_tags]
        valid_tags: List[str] = []
        for t in list(raw_tags) + overflow_tags:
            clean_t = str(t).strip().lower()
            if clean_t and clean_t not in valid_tags:
                valid_tags.append(clean_t)

        # 3. Normalize Language
        raw_lang = raw_data.get("language")
        valid_lang: Optional[str] = None
        if raw_lang and isinstance(raw_lang, str):
            valid_lang = known_languages_map.get(raw_lang.strip().lower())

        # 4. Normalize Content Type
        raw_type = raw_data.get("content_type")
        valid_type: Optional[str] = None
        if raw_type and isinstance(raw_type, str):
            norm_type = raw_type.strip().lower()
            if norm_type in {"movie", "film"}:
                valid_type = "Movie"
            elif norm_type in {"series", "show", "tv"}:
                valid_type = "Series"

        # 5. Normalize Duration
        raw_dur = raw_data.get("max_duration_minutes")
        valid_dur: Optional[int] = None
        if raw_dur is not None:
            try:
                parsed_dur = int(raw_dur)
                if parsed_dur > 0:
                    valid_dur = parsed_dur
            except (ValueError, TypeError):
                valid_dur = None

        # Duration category
        raw_cat = raw_data.get("duration_category")
        valid_cat: Optional[str] = None
        if raw_cat and isinstance(raw_cat, str):
            norm_cat = raw_cat.strip().lower()
            if norm_cat in {"quick", "standard", "epic"}:
                valid_cat = norm_cat

        return UserPreferences(
            genres=valid_genres,
            language=valid_lang,
            content_type=valid_type,
            moods=valid_moods,
            tags=valid_tags[:10],
            max_duration_minutes=valid_dur,
            duration_category=valid_cat,
        )


_default_gemini_service: Optional[GeminiService] = None


def get_gemini_service(
    api_key: Optional[str] = None,
    catalog_service: Optional[CatalogService] = None,
) -> GeminiService:
    """Accessor for the singleton/default GeminiService instance."""
    global _default_gemini_service
    if _default_gemini_service is None or api_key is not None:
        _default_gemini_service = GeminiService(
            api_key=api_key, catalog_service=catalog_service
        )
    return _default_gemini_service
